### PR TITLE
worker - attempt to avoid syntax errors from arbitrary modules

### PR DESCRIPTION
**Pull request by s-cork**
address #90 

@rhurlbatt - try this - I'm not sure it'll work but it's potentially an easy fix if it does work.

If it doesn't i'll have a think
It's probably some python source code that javascript doesn't like
I had a few ideas - but couldn't reproduce it in a toy example.

### CODE REVIEW

**Comment by s-cork** [comment]
merging - bugfix (attempt)

**Comment by rhurlbatt** [comment]
No dice using the development branch unfortunately - it still throws the same error and I cannot get it to reproduce in a sample app either. Is there anything I can get from the console that will help?

**Comment by s-cork** [comment]
That's a shame
Try replacing that `<script src="_/theme/anvil-labs/worker.js" defer></script>`
with
`<script src="https://raw.githubusercontent.com/anvilistas/anvil-labs/worker-debug/theme/assets/anvil-labs/worker.js" defer></script>`

Open up the browser console and see if there are any errors
It might pin point which python file is causing the problem
You should see 
`SUCCESS:<filename>` in green and then maybe at some point...
`PROBLEM LOADING <filename>` in red in the browser console.

If we only get successes then at least we'll know which files load before the web worker tries to load before attempting to run the web worker.
We can then go from there.

**Comment by s-cork** [comment]
I edited the post. If you check the url it's not the same.

**Comment by rhurlbatt** [comment]
I see that now 🤦 - yep error still occurring. I can try clone one of the smaller apps tomorrow and see if I can get it to replicate - or happy to create a virtual session to poke through one of the existing apps if that fails?

**Comment by s-cork** [comment]
The error should still occur with the other url, but was there any useful browser console output? There should have been a bunch of green success messages and maybe one or more red failures?

Smaller apps with reproduction cases would be best. But otherwise can also do a virtual session.

**Comment by rhurlbatt** [comment]
Sorry it might have to be a virtual session - I have tried ALOT and cannot get it to reproduce in a smaller app. Will touch base via email

**Comment by s-cork** [comment]
No worries - thanks for trying!

**Pull request merged**
