### PR TITLE
zod: try out pythonic names

### PR DESCRIPTION
**Pull request by s-cork**
Just drafting this so I can sleep on the idea
but let me know what you think @meatballs 

I think, at the moment, I prefer this, since it's closer to python's typing names
`z.typeddict` is a bit verbose but hey... I didn't choose it

I've left the TypeScript names in as aliases for convenience

See #120 for context

### CODE REVIEW

**Comment by meatballs** [comment]
It seems better to match the typing names, even if they're not what we might have chosen

**Comment by s-cork** [comment]
merci
do you think remove the aliases?
Or just leave them in and not document them (whenever I get round to that)

**Comment by meatballs** [comment]
The latter, I reckon

**Comment by meatballs** [comment]
General convention is to convert camel case to snake, so the underscored option.

**Comment by s-cork** [comment]
But maybe it can be like namedtuple?

**Comment by meatballs** [comment]
There's plenty of stuff in the standard lib that was written well before pep8 existed and doesn't conform to it.

I don't think that justifies non-conformance today.

**Comment by s-cork** [comment]
Ok - names changed - ready I think

**Pull request merged**
