### PR TITLE
Convert class name to snake case

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by s-cork** [comment]
re.sub isn't available on the client unfortunately. 

(You can bug meredydd on that one. There's a rewrite of the re module that's been sitting there for years)

**Comment by meatballs** [comment]
Damn. time for a rewrite...

**Comment by meatballs** [comment]
Waiting for https://github.com/skulpt/skulpt/pull/1206 before we can do a proper job.

**Comment by s-cork** [comment]
You might want to go with a non regex solution. Or adjust the regex. Look behind assertions aren't supported in safari 😔

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility


Something like:

```python

def to_snake(s):
    first, rest = s[0], s[1:]
    return first.lower() + ''.join('_' + x.lower() if x.isupper() else x for x in rest)

```

**Comment by meatballs** [comment]
I did something along those lines in the last commit. Is there something in there you don't like?

**Comment by s-cork** [comment]
Ah no I just missed that commit. 

Remove the square brackets and we're good to merge 😉

**Comment by meatballs** [comment]
Must learn to check stuff I'm copying and pasting from elsewhere - even when it's my own code!

**Pull request merged**
