### PR TITLE
SW: bg sync with fallback

### PR DESCRIPTION
**Pull request by s-cork**
Adds fallback support for background sync
backwards incompatible

rather than doing 

```python

@sync_event_handler
def on_sync(e):
    if e.tag != "my_tag":
        return

self.onsync = on_sync
    
```

instead do

```python

def on_sync():
    ...

self.BackgroundSync("my_tag", on_sync)
    
```

### CODE REVIEW

**Comment by s-cork** [comment]
Current dependencies on/for this PR:
* main
  * **PR #146** <a href="https://app.graphite.dev/github/pr/anvilistas/anvil-labs/146?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/anvilistas/anvil-labs/146?utm_source=stack-comment).

**Comment by s-cork** [comment]
@rhurlbatt  - any questions before merging?

**Comment by Rick-VIPER** [comment]
@s-cork no we are good. Production is still running on the Web Worker so this shouldnt break anything for us. Thanks for checking.

**Comment by s-cork** [comment]
Here's the diff for the demo app:
https://github.com/anvilistas/service-worker-demo/pull/1

Otherwise everything else remains the same

**Pull request merged**
